package org.om.jcr2pojo.classgenerator;

import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.Date;

import org.om.jcr2pojo.exception.JCR2POJOException;

/**
 * 
 * @author tome
 * 
 */
public class DAOGenerator {
	/**
	 * generate a POJO
	 */
	public void generateDAO(String className, String namespace, OutputStream outputStream) throws JCR2POJOException {
		try {
			/*
			 * writer
			 */
			final PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputStream));
			/*
			 * namespace
			 */
			writer.println("package " + namespace + ";");
			writer.println();
			/*
			 * mr. everett's magic imports
			 */
			writer.println("org.om.dao.api.GenericDAO;");
			writer.println("org.om.dao.impl.GenericDAOImpl;");
			writer.println();
			/*
			 * some commentary at the top
			 */
			writer.println("/*");
			writer.println("* <p>This is a generated class</p>");
			writer.println("* <p>Do not edit this file, changes will be overwritten!</p>");
			writer.println("* <p>Generated: " + new Date().toString() + "</p>");
			writer.println("* <p>Generated on: " + java.net.InetAddress.getLocalHost().getHostName() + "</p>");
			writer.println("* <p>Generated by: " + System.getProperty("user.name") + "</p>");
			writer.println("*/");
			/*
			 * declare the class
			 */
			writer.println("public class " + className + "DAO extends GenericDAOImpl<" + className + "> implements GenericDAO<" + className + "> " + "{");
			writer.println();
			/*
			 * ctor
			 */
			writer.println("public " + className + "DAO() {super(" + className + ".class);}");
			/*
			 * end of class
			 */
			writer.println("}");
			/*
			 * done
			 */
			writer.flush();
			writer.close();
		} catch (final Exception e) {
			throw new JCR2POJOException("Exception in generateDAO", e);
		}
	}

}
